---
- name: Generate FRR configuration file from template
  ansible.builtin.template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    owner: frr
    group: frr
    mode: "0644"

- name: Restart FRR service
  ansible.builtin.service:
    name: frr
    state: restarted
