name: Deploy FRR Config

on:
  push:
    branches:
      - main
    paths:
      - 'playbook.yaml'
      - 'inventory.yaml'
      - 'roles/**'
      - '*.conf'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure pip is installed
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip

      - name: Install Ansible Lint
        run: |
          pip install ansible-lint

      - name: Auto-fix Ansible Lint issues
        run: |
          ansible-lint --fix playbook.yaml roles

      - name: Validate Lint After Fix
        run: |
          ansible-lint playbook.yaml roles

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i inventory.yaml playbook.yaml
